window.SAYISTAY_DATA.quizzes[5] = {
  title: "İktisat — 20 Soruluk Gün Sonu Testi",
  questions: [
    {q:"Tam rekabet piyasasında tek bir firmanın karşılaştığı talep eğrisi nasıldır?",o:["Negatif eğimli","Pozitif eğimli","Yatay","Dikey","Önce artan sonra azalan"],a:2,e:"Firma fiyat alıcıdır; piyasa fiyatından istediği kadar satabildiği varsayılır."},
    {q:"Tam rekabette kısa dönem kâr maksimizasyon koşulu hangisidir?",o:["P=AC her zaman","MR=MC","TR=TC zorunlu","AR=0","MC=0"],a:1,e:"Kâr maksimizasyonunun genel koşulu MR=MC'dir; tam rekabette ayrıca P=MR=AR'dır."},
    {q:"Tam rekabetçi firma uzun dönemde normal kârdayken hangi ilişki beklenir?",o:["P>AC","P<AVC","P=min AC","MR=0","MC=0"],a:2,e:"Serbest giriş-çıkış uzun dönemde ekonomik kârı sıfıra iter; denge minimum ortalama maliyette oluşur."},
    {q:"Monopolcünün talep eğrisi için hangisi doğrudur?",o:["Yataydır","Piyasa talep eğrisidir ve negatif eğimlidir","Dikeydir","Tam esnektir","Arz eğrisiyle aynıdır"],a:1,e:"Tek satıcı olduğundan firmanın talebi piyasa talebidir."},
    {q:"Doğrusal, negatif eğimli talep altında monopolde marjinal gelir için hangisi doğrudur?",o:["Talep eğrisinin üstündedir","Talep eğrisiyle aynıdır","Talep eğrisinin altında seyreder","Daima sıfırdır","Daima negatiftir"],a:2,e:"Daha fazla satmak için fiyat düşürüldüğünden MR, fiyatın/talebin altındadır."},
    {q:"Monopol kâr maksimizasyonunda üretim miktarı önce hangi eşitlikle belirlenir?",o:["P=MC","MR=MC","P=AC","AR=AC","TR=TC"],a:1,e:"Önce MR=MC ile miktar bulunur, sonra talep eğrisinden fiyat okunur."},
    {q:"Aşağıdakilerden hangisi monopol gücünün kaynağı olabilir?",o:["Tam bilgi","Serbest giriş","Patent","Homojen mal zorunluluğu","Çok sayıda satıcı"],a:2,e:"Patent gibi giriş engelleri monopol gücü yaratabilir."},
    {q:"Fiyat farklılaştırmasının temel şartlarından biri hangisidir?",o:["Piyasalar arasında yeniden satışın kolay olması","Pazarların ayrıştırılabilmesi","Tüm tüketicilerin aynı esnekliğe sahip olması","Tam rekabet olması","Fiyatın devletçe tek belirlenmesi"],a:1,e:"Firma tüketici/pazar gruplarını ayırabilmeli ve arbitrajı sınırlayabilmelidir."},
    {q:"Monopolcü rekabetin ayırt edici özelliği hangisidir?",o:["Tek firma","Homojen ürün zorunluluğu","Farklılaştırılmış ürün ve çok sayıda firma","Girişin tamamen yasak olması","Firmanın talebinin yatay olması"],a:2,e:"Çok sayıda firma vardır ancak ürünler farklılaştırılmıştır."},
    {q:"Monopolcü rekabette uzun dönemde ekonomik kâr neden sıfıra yaklaşır?",o:["Devlet fiyatı sabitler","Serbest giriş-çıkış","MR daima sıfırdır","Maliyet yoktur","Talep dikeydir"],a:1,e:"Pozitif kâr yeni firmaları çeker; talep firma başına azalır."},
    {q:"Monopolcü rekabette uzun dönem dengesi genellikle hangi sonucu doğurur?",o:["Minimum AC'de üretim zorunlu","Atıl kapasite","Tam etkinlik","P=MC","Homojen ürün"],a:1,e:"Firma çoğu kez minimum ortalama maliyetin solunda üretir; bu atıl kapasite olarak anılır."},
    {q:"Oligopol piyasasının temel özelliği hangisidir?",o:["Firmaların kararlarının birbirinden bağımsız olması","Az sayıda firma ve stratejik karşılıklı bağımlılık","Tek satıcı","Sonsuz firma","Giriş engelinin hiç olmaması"],a:1,e:"Her firmanın kararı rakiplerin davranışını ve tepkisini dikkate alır."},
    {q:"Kartel hangi piyasa yapısıyla en yakından ilişkilidir?",o:["Tam rekabet","Monopolcü rekabet","Oligopol","Monopson","İki taraflı monopol"],a:2,e:"Oligopol firmaları fiyat/üretim konusunda anlaşarak kartel oluşturabilir."},
    {q:"Cournot modelinde firmaların temel stratejik değişkeni nedir?",o:["Fiyat","Üretim miktarı","Reklam","Ücret","Faiz"],a:1,e:"Klasik Cournot modelinde firmalar miktar seçer."},
    {q:"Bertrand modelinin klasik sürümünde firmaların temel stratejik değişkeni nedir?",o:["Miktar","Fiyat","Kalite","Ücret","Vergi"],a:1,e:"Bertrand rekabetinde firmalar fiyat belirleyerek rekabet eder."},
    {q:"Kinked demand (dirsekli talep) modeli en çok neyi açıklamak için kullanılır?",o:["Tam rekabette uzun dönem kârını","Oligopolde fiyat katılığını","Monopolde fiyat farklılaştırmasını","Tüketici dengesini","Üretim fonksiyonunu"],a:1,e:"Rakiplerin fiyat değişikliklerine asimetrik tepki vereceği beklentisi fiyat katılığını açıklar."},
    {q:"Tam rekabet ile monopol karşılaştırıldığında, aynı talep ve maliyet koşullarında monopol için genel beklenti hangisidir?",o:["Daha düşük fiyat, daha yüksek miktar","Daha yüksek fiyat, daha düşük miktar","Aynı fiyat ve miktar zorunlu","Fiyat sıfır","Miktar sonsuz"],a:1,e:"Monopol üretimi kısarak daha yüksek fiyat uygular; refah kaybı doğabilir."},
    {q:"Bir tam rekabet firmasında piyasa fiyatı AVC'nin minimumunun altına düşerse kısa dönemde ne yapması beklenir?",o:["Üretimi artırır","Üretime aynen devam eder","Üretimi durdurur","Yeni firma kurar","Fiyatı tek başına yükseltir"],a:2,e:"Fiyat minimum AVC'nin altındaysa değişken maliyetler dahi karşılanamaz; kapanma kararı verilir."},
    {q:"Monopolcü rekabette firmanın talep eğrisinin negatif eğimli olmasının temel nedeni nedir?",o:["Ürün farklılaştırması nedeniyle sınırlı fiyat gücü","Devletin fiyat belirlemesi","Ürünün tamamen homojen olması","Sonsuz esneklik","Maliyetlerin sabit olması"],a:0,e:"Farklılaştırma firmaya yakın ikameler karşısında sınırlı piyasa gücü verir."},
    {q:"Bir oligopol firması fiyatını düşürdüğünde rakiplerin de fiyat düşürmesi, fakat fiyat artırdığında rakiplerin izlememesi varsayımı hangi sonuca katkı verir?",o:["Talebin tamamen yatay olmasına","Fiyat katılığına","Monopolün yok olmasına","Tam rekabete geçişe","Marjinal maliyetin sıfırlanmasına"],a:1,e:"Dirsekli talep yaklaşımında bu asimetrik tepki mevcut fiyat çevresinde katılık yaratır."}
  ]
};