window.SAYISTAY_DATA.quizzes[2] = {
  title: "İktisat — 20 Soruluk Gün Sonu Testi",
  questions: [
    {q:"İktisatta kıtlık kavramı neyi ifade eder?",o:["Tüm malların fiziksel olarak az olmasını","İhtiyaçlara göre kaynakların sınırlı olmasını","Paranın tamamen yokluğunu","Üretimin sıfır olmasını"],a:1,e:"Kıtlık, sınırsız sayılabilecek ihtiyaçlara karşı kaynakların sınırlı olmasıdır."},
    {q:"Bir tercih nedeniyle vazgeçilen en iyi alternatifin değeri nedir?",o:["Marjinal fayda","Fırsat maliyeti","Sabit maliyet","Tüketici rantı"],a:1,e:"Fırsat maliyeti, seçilen seçenek uğruna vazgeçilen en değerli alternatifin değeridir."},
    {q:"Üretim imkânları eğrisinin içindeki bir nokta neyi gösterir?",o:["Ulaşılamaz üretim düzeyi","Kaynakların tam ve etkin kullanımı","Eksik veya etkin olmayan kaynak kullanımı","Teknolojik ilerleme"],a:2,e:"Eğrinin içindeki noktalar mevcut kaynak ve teknolojiyle ulaşılabilir ancak etkin olmayan üretimi gösterir."},
    {q:"Teknolojik gelişme üretim imkânları eğrisini genel olarak nasıl etkiler?",o:["İçe kaydırır","Değiştirmez","Dışa kaydırır","Dikey yapar"],a:2,e:"Teknolojik gelişme aynı kaynaklarla daha fazla üretim olanağı sağladığından üretim imkânları eğrisini dışa kaydırır."},
    {q:"Bir malın kendi fiyatı düşerken diğer koşullar sabit kaldığında ne olur?",o:["Talep eğrisi sağa kayar","Talep eğrisi sola kayar","Talep edilen miktar artar","Arz azalır"],a:2,e:"Kendi fiyatındaki değişme talep eğrisi üzerinde hareket yaratır; fiyat düşünce talep edilen miktar artar."},
    {q:"Kahve fiyatı artınca çay talebi artıyorsa çay ile kahve arasındaki ilişki nedir?",o:["Tamamlayıcı","İkame","Bağımsız","Düşük mal"],a:1,e:"Bir malın fiyatı yükseldiğinde diğerine talep artıyorsa mallar ikamedir."},
    {q:"Normal bir malda tüketici geliri arttığında diğer koşullar sabitken ne beklenir?",o:["Talep azalır","Talep artar","Arz azalır","Fiyat zorunlu olarak düşer"],a:1,e:"Normal mallarda gelir artışı talep eğrisini sağa kaydırır."},
    {q:"Üretimde kullanılan temel bir girdinin fiyatı artarsa arz eğrisi genel olarak nasıl değişir?",o:["Sağa kayar","Dikey olur","Sola kayar","Değişmez"],a:2,e:"Girdi maliyetinin yükselmesi üretim maliyetini artırır ve arzı azaltarak eğriyi sola kaydırır."},
    {q:"Piyasa fiyatı denge fiyatının altında tutulursa genel olarak hangi durum oluşur?",o:["Arz fazlası","Talep fazlası/kıtlık","Denge miktarı değişmez","Talep ortadan kalkar"],a:1,e:"Denge fiyatının altında talep edilen miktar arz edilen miktarı aşar; talep fazlası oluşur."},
    {q:"Arz sabitken talep artarsa denge fiyatı ve denge miktarı için ne beklenir?",o:["İkisi de azalır","Fiyat düşer, miktar artar","İkisi de artar","Fiyat artar, miktar azalır"],a:2,e:"Talebin sağa kayması, normal eğim varsayımı altında hem denge fiyatını hem miktarı artırır."},
    {q:"Talep ve arzın aynı anda artması halinde hangi sonuç kesin olarak söylenebilir?",o:["Denge fiyatı artar","Denge miktarı artar","Denge fiyatı düşer","Denge miktarı azalır"],a:1,e:"Her iki eğrinin sağa kayması denge miktarını artırır; fiyatın yönü kaymaların büyüklüğüne bağlıdır."},
    {q:"Bir malın fiyatı %10 düşerken talep edilen miktar %20 artıyorsa talebin fiyat esnekliğinin mutlak değeri kaçtır?",o:["0,5","1","1,5","2"],a:3,e:"|Ed| = % miktar değişimi / % fiyat değişimi = 20/10 = 2."},
    {q:"Talep esnekse fiyat düşüşünün toplam hasıla üzerindeki genel etkisi nedir?",o:["Toplam hasıla artar","Toplam hasıla azalır","Toplam hasıla değişmez","Hasıla sıfırlanır"],a:0,e:"Esnek talepte miktardaki yüzde değişim fiyat değişiminden büyük olduğu için fiyat düşüşü toplam hasılayı artırır."},
    {q:"Gelir esnekliği negatif olan bir mal nasıl adlandırılır?",o:["Normal mal","Lüks mal","Düşük mal","İkame mal"],a:2,e:"Gelir artarken talep azalıyorsa gelir esnekliği negatiftir ve mal düşük maldır."},
    {q:"Çapraz talep esnekliği pozitif olan iki mal genellikle nasıl ilişkilidir?",o:["Tamamlayıcı","Bağımsız","İkame","Kamusal"],a:2,e:"Bir malın fiyatı artarken diğer mala talep artıyorsa çapraz esneklik pozitiftir ve mallar ikamedir."},
    {q:"Tüketicilerin uyum sağlamak için daha fazla zamanı olduğunda talebin fiyat esnekliği genel olarak nasıl değişir?",o:["Azalır","Sıfır olur","Artar","Mutlaka bir olur"],a:2,e:"Zaman arttıkça tüketiciler ikame seçeneklere daha kolay yöneldiğinden talep genellikle daha esnek hale gelir."},
    {q:"Marjinal fayda pozitif fakat azalıyorsa toplam fayda nasıl değişir?",o:["Azalır","Artar fakat artış hızı yavaşlar","Sabit kalır","Negatif olur"],a:1,e:"Marjinal fayda pozitif olduğu sürece toplam fayda artar; marjinal fayda azaldıkça toplam faydanın artış hızı düşer."},
    {q:"Toplam faydanın maksimum olduğu noktada marjinal fayda için genel olarak ne söylenir?",o:["Sonsuzdur","Pozitiftir","Sıfırdır","Daima negatiftir"],a:2,e:"Toplam faydanın tepe noktasında ilave birimin toplam faydaya katkısı sıfırdır."},
    {q:"Kardinal fayda yaklaşımında iki mal tüketen tüketicinin dengesi için temel koşul hangisidir?",o:["MUx = MUy","MUx/Px = MUy/Py","Px = Py","TUx = TUy"],a:1,e:"Tüketici, son harcanan para biriminin marjinal faydasını mallar arasında eşitler: MUx/Px = MUy/Py."},
    {q:"Bir malın üretim teknolojisindeki iyileşme ile tüketici zevklerindeki artış aynı anda gerçekleşirse hangi eğriler etkilenir?",o:["Yalnız talep","Yalnız arz","Teknoloji arzı, zevk değişimi talebi etkiler","Hiçbiri"],a:2,e:"Teknolojik iyileşme arzı artırır; mal lehine zevk değişimi talebi artırır. Fiyatın nihai yönü kaymaların büyüklüğüne bağlı olabilir."}
  ]
};