window.SAYISTAY_DATA.quizzes[3] = {
  title: "Muhasebe — 20 Soruluk Gün Sonu Testi",
  questions: [
    {q:"Temel muhasebe eşitliği hangisidir?",o:["Varlıklar = Borçlar + Öz Kaynaklar","Varlıklar = Gelirler - Giderler","Borçlar = Varlıklar + Öz Kaynaklar","Gelirler = Varlıklar + Borçlar"],a:0,e:"Temel bilanço eşitliği varlıkların yabancı kaynaklar ve öz kaynaklarla finanse edildiğini gösterir."},
    {q:"Bir varlık hesabındaki artış normal olarak hangi tarafa kaydedilir?",o:["Alacak","Borç","Nazım","Kapanış"],a:1,e:"Aktif karakterli hesaplarda artışlar borç, azalışlar alacak tarafına kaydedilir."},
    {q:"Bir kaynak hesabındaki artış normal olarak hangi tarafa kaydedilir?",o:["Borç","Alacak","Her iki tarafa eşit","Nazım"],a:1,e:"Pasif karakterli kaynak hesaplarında artışlar alacak tarafına kaydedilir."},
    {q:"Dönemsellik kavramı neyi gerektirir?",o:["Tüm işlemlerin peşin yapılmasını","Gelir ve giderlerin ait oldukları dönemde muhasebeleştirilmesini","Sadece nakit işlemlerin kaydedilmesini","Tüm hesapların yıl içinde kapatılmasını"],a:1,e:"Dönemsellik, faaliyet sonuçlarının belirli dönemlere ayrılarak gelir ve giderlerin ilgili döneme yüklenmesini gerektirir."},
    {q:"Kişilik kavramı neyi ifade eder?",o:["İşletmenin sahibinden ayrı bir muhasebe kişiliği kabul edilmesini","Sadece gerçek kişilerin işletme kurmasını","Tüm borçların işletme sahibine ait olmasını","Muhasebenin yalnız vergi için tutulmasını"],a:0,e:"İşletme, sahiplerinden ayrı bir ekonomik ve muhasebe kişiliği olarak ele alınır."},
    {q:"Tek Düzen Hesap Planında 1 numaralı hesap sınıfı hangisidir?",o:["Duran Varlıklar","Kısa Vadeli Yabancı Kaynaklar","Dönen Varlıklar","Öz Kaynaklar"],a:2,e:"1 Dönen Varlıklar, 2 Duran Varlıklar, 3 Kısa Vadeli Yabancı Kaynaklar, 4 Uzun Vadeli Yabancı Kaynaklar, 5 Öz Kaynaklar şeklinde ilerler."},
    {q:"Muhasebe belge ve kayıt akışında doğru sıra hangisidir?",o:["Mizan → Yevmiye → Büyük Defter","Büyük Defter → Belge → Yevmiye","Belge → Yevmiye Defteri → Büyük Defter → Mizan","Yevmiye → Belge → Mizan → Büyük Defter"],a:2,e:"İşlem belgelendirilir, yevmiye defterine kronolojik kaydedilir, büyük deftere aktarılır ve mizanla hesapların dengesi kontrol edilir."},
    {q:"Mizanın temel işlevlerinden biri hangisidir?",o:["Varlıkların piyasa değerini belirlemek","Borç ve alacak toplamlarının eşitliğini kontrol etmek","Vergi oranını belirlemek","Faturayı düzenlemek"],a:1,e:"Mizan, hesapların borç/alacak toplam ve bakiyelerini topluca göstererek kayıtların aritmetik kontrolüne yardımcı olur."},
    {q:"100 Kasa hesabı hangi gruptadır?",o:["Ticari Alacaklar","Hazır Değerler","Maddi Duran Varlıklar","Öz Kaynaklar"],a:1,e:"100 Kasa, 102 Bankalar gibi hesaplar Hazır Değerler grubunda yer alır."},
    {q:"102 Bankalar hesabının borçlandırılması genel olarak neyi gösterir?",o:["Banka mevduatının artmasını","Banka mevduatının azalmasını","Sermayenin azalmasını","Ticari borcun artmasını"],a:0,e:"Bankalar bir varlık hesabıdır; mevduat artışları hesabın borcuna kaydedilir."},
    {q:"Senetsiz ticari alacaklar hangi hesapta izlenir?",o:["121 Alacak Senetleri","120 Alıcılar","320 Satıcılar","100 Kasa"],a:1,e:"Müşterilerden olan senetsiz ticari alacaklar 120 Alıcılar hesabında izlenir."},
    {q:"Senetli ticari alacaklar hangi hesapta izlenir?",o:["120 Alıcılar","121 Alacak Senetleri","321 Borç Senetleri","102 Bankalar"],a:1,e:"Senede bağlanmış ticari alacaklar 121 Alacak Senetleri hesabında izlenir."},
    {q:"10.000 TL'lik malın peşin satın alınması, KDV ihmal edilirse, toplam varlıkları nasıl etkiler?",o:["10.000 TL artırır","10.000 TL azaltır","Toplam varlık değişmez, varlık yapısı değişir","Öz kaynak 10.000 TL artar"],a:2,e:"Kasa azalırken stok artar; bir varlık diğerine dönüşür ve toplam varlık değişmez."},
    {q:"20.000 TL banka kredisi çekilip tutar banka hesabına yatırılırsa muhasebe eşitliği nasıl etkilenir?",o:["Varlık ve borç 20.000 TL artar","Varlık artar, borç azalır","Öz kaynak 20.000 TL artar","Yalnız varlık artar"],a:0,e:"Banka mevduatı varlık olarak artarken banka kredisi yabancı kaynak olarak aynı tutarda artar."},
    {q:"Müşteriden olan 120 Alıcılar hesabındaki alacak banka yoluyla tahsil edilirse ne olur?",o:["120 artar, 102 azalır","120 azalır, 102 artar","Her ikisi de azalır","Öz kaynak artar"],a:1,e:"Alacağın tahsilinde 120 Alıcılar alacaklandırılarak azalır, 102 Bankalar borçlandırılarak artar."},
    {q:"Yevmiye defteri ile büyük defter arasındaki temel fark hangisidir?",o:["İkisi tamamen aynıdır","Yevmiye kronolojik, büyük defter hesap bazında sınıflandırılmış kayıt tutar","Büyük defter sadece yıl sonunda kullanılır","Yevmiye sadece nakit işlemleri içerir"],a:1,e:"Yevmiye işlemleri tarih sırasıyla, büyük defter ise ilgili hesaplara göre sınıflandırarak gösterir."},
    {q:"Bir aktif hesabın borç toplamı 80.000 TL, alacak toplamı 50.000 TL ise bakiye nedir?",o:["30.000 TL borç bakiyesi","30.000 TL alacak bakiyesi","130.000 TL borç bakiyesi","Bakiye yoktur"],a:0,e:"Aktif hesabın borç toplamı alacak toplamını 30.000 TL aştığı için 30.000 TL borç bakiyesi vardır."},
    {q:"İhtiyatlılık kavramı en çok hangi yaklaşımı ifade eder?",o:["Muhtemel zarar ve risklerin dikkate alınması","Tüm gelirlerin peşinen kaydedilmesi","Varlıkların daima en yüksek değerle gösterilmesi","Borçların kayda alınmaması"],a:0,e:"İhtiyatlılık, belirsizliklerde temkinli davranmayı; muhtemel risk ve zararların dikkate alınmasını öngörür."},
    {q:"KDV ve maliyet kaydı ihmal edilerek vadeli mal satışı yapıldığında temel kayıt hangisidir?",o:["120 Alıcılar borç / Satış Geliri alacak","Satış Geliri borç / 120 Alıcılar alacak","100 Kasa borç / 320 Satıcılar alacak","153 Ticari Mallar borç / 120 Alıcılar alacak"],a:0,e:"Vadeli satışta müşteriden alacak doğar; 120 Alıcılar borçlandırılır ve satış geliri alacaklandırılır."},
    {q:"Mizanda borç ve alacak toplamlarının eşit çıkması neyi kesin olarak kanıtlar?",o:["Tüm kayıtların tamamen doğru olduğunu","Hiç hata olmadığını","Yalnızca aritmetik dengenin bulunduğunu; bazı hataların yine de mümkün olduğunu","Tüm belgelerin hukuken geçerli olduğunu"],a:2,e:"Mizan eşitliği aritmetik dengeyi gösterir; yanlış hesaba eşit tutarlı kayıt gibi bazı hataları ortaya çıkaramayabilir."}
  ]
};