window.SAYISTAY_DATA.quizzes[4] = {
  title: "Maliye — 20 Soruluk Gün Sonu Testi",
  questions: [
    {q:"Verginin kanuniliği ilkesi neyi ifade eder?",o:["Verginin temel unsurlarının kanunla düzenlenmesini","Verginin yalnız belediyelerce alınmasını","Vergi oranlarının her yıl artmasını","Verginin yalnız gelir üzerinden alınmasını"],a:0,e:"Verginin konusu, mükellefi, matrahı, oranı ve benzeri temel unsurlar kanuni dayanağa sahip olmalıdır."},
    {q:"Vergilemede ödeme gücü ilkesi neyi amaçlar?",o:["Herkesten aynı tutarda vergi alınmasını","Kişilerin mali güçleri ölçüsünde kamu giderlerine katılmasını","Yalnız tüketimin vergilenmesini","Verginin tamamen gönüllü olmasını"],a:1,e:"Ödeme gücü yaklaşımı, vergi yükünün ekonomik güç dikkate alınarak dağıtılmasını amaçlar."},
    {q:"Objektif vergi yükü en basit biçimde nasıl ifade edilir?",o:["Vergi matrahı / gelir","Ödenen vergi / gelir veya ödeme gücü göstergesi","Kamu harcaması / nüfus","Borç / ihracat"],a:1,e:"Objektif vergi yükü, ödenen verginin gelir gibi bir ödeme gücü göstergesine oranlanmasıyla ölçülür."},
    {q:"Verginin ileriye yansıması neyi ifade eder?",o:["Vergi yükünün üretim faktörlerine aktarılmasını","Verginin satış fiyatına eklenerek alıcıya aktarılmasını","Verginin geçmiş döneme taşınmasını","Verginin tamamen ortadan kalkmasını"],a:1,e:"İleriye yansımada vergi, daha yüksek fiyat yoluyla sonraki alıcıya/tüketiciye aktarılır."},
    {q:"Bir malın talebi çok esnek, arzı görece daha az esnek ise birim verginin daha büyük kısmını kim taşıma eğilimindedir?",o:["Tüketici","Üretici","Devlet","Hiç kimse"],a:1,e:"Vergi yükü, esnekliği daha düşük olan taraf üzerinde daha fazla kalır; talep çok esnekse üretici fiyatı tüketiciye aktarmakta zorlanır."},
    {q:"Vergi kapasitesi neyi ifade eder?",o:["Fiilen tahsil edilen vergi tutarını","Bir ekonominin potansiyel olarak taşıyabileceği vergi düzeyini","Yalnız dolaylı vergi toplamını","Vergi idaresinin personel sayısını"],a:1,e:"Vergi kapasitesi ekonomik ve sosyal yapı dikkate alındığında ulaşılabilecek potansiyel vergi düzeyidir."},
    {q:"Vergi gayreti neyi gösterir?",o:["Vergi kapasitesinin ne ölçüde fiili vergi hasılatına dönüştürüldüğünü","Kamu borcunun vadesini","Vergi oranının tek başına yüksekliğini","Kamu harcamasının büyüklüğünü"],a:0,e:"Vergi gayreti, mevcut vergi kapasitesinin ne derece kullanıldığını anlatır."},
    {q:"Aşağıdakilerden hangisi olağan kamu gelirlerine örnektir?",o:["Vergi","Savaş tazminatı","Bir defalık özelleştirme geliri zorunlu olarak","Merkez bankasından sürekli avans"],a:0,e:"Vergiler, kamu gelirlerinin en temel ve olağan kaynaklarındandır."},
    {q:"Kamu borçlanmasının vergiden temel farklarından biri hangisidir?",o:["Hiç kaynak sağlamaması","Genellikle geri ödeme yükümlülüğü doğurması","Yalnız özel kesimce yapılması","Zorunlu olarak karşılıksız olması"],a:1,e:"Borçlanma gelecekte anapara ve çoğu kez faiz ödeme yükümlülüğü doğurur; vergi ise kural olarak karşılıksız kamu geliridir."},
    {q:"Aşağıdakilerden hangisi iç borç kaynağına örnektir?",o:["Yabancı devlet","Ülke içindeki kişi ve kurumlar","Uluslararası kuruluş","Yabancı banka zorunlu olarak"],a:1,e:"İç borçlanmada kaynak ekonominin kendi yerleşiklerinden veya iç mali piyasadan sağlanır."},
    {q:"Genişletici maliye politikası için hangisi doğrudur?",o:["Kamu harcamaları azaltılır ve vergiler artırılır","Kamu harcamaları artırılabilir ve/veya vergiler azaltılabilir","Para arzı mutlaka azaltılır","Döviz kuru sabitlenir"],a:1,e:"Genişletici maliye politikası toplam talebi artırmak için kamu harcamalarını artırma ve/veya vergileri azaltma yönünde uygulanabilir."},
    {q:"Durgunluk ve yüksek işsizlik koşullarında hangi maliye politikası yönü genellikle tercih edilir?",o:["Daraltıcı","Genişletici","Tarafsız para politikası zorunlu","Vergi dışı gelirleri sıfırlama"],a:1,e:"Durgunlukta amaç toplam talebi ve üretimi desteklemek olduğundan genişletici maliye politikası gündeme gelir."},
    {q:"Kamu harcamalarındaki ilk artışın milli gelirde daha büyük bir artış yaratmasına ne ad verilir?",o:["Dışlama","Çarpan etkisi","Yansıma","Konversiyon"],a:1,e:"Harcama artışı gelir yaratır; bu gelirin bir kısmı yeniden harcandıkça toplam gelirde katlı artış ortaya çıkar."},
    {q:"Marjinal tüketim eğilimi yükselirse basit harcama çarpanı genel olarak nasıl değişir?",o:["Küçülür","Büyür","Sıfırlanır","Değişmez"],a:1,e:"Basit modelde k = 1/(1-c). Marjinal tüketim eğilimi c arttıkça payda küçülür ve çarpan büyür."},
    {q:"Artan oranlı gelir vergisinin otomatik istikrar sağlayıcı etkisi nasıl çalışır?",o:["Gelir yükselirken vergi yükünü otomatik artırıp talep artışını sınırlar; gelir düşerken ters yönde tampon olur","Her durumda aynı tutarda vergi alır","Yalnız kamu borcunu azaltır","Para arzını doğrudan artırır"],a:0,e:"Artan oranlı vergiler konjonktüre karşı otomatik çalışarak toplam talepteki dalgalanmaları yumuşatabilir."},
    {q:"Aşağıdakilerden hangisi klasik anlamda maliye politikasının temel amaçlarından biri değildir?",o:["Fiyat istikrarı","Tam istihdam","Ekonomik büyüme","Gelir dağılımında iyileşme","Tek bir nominal döviz kurunu her koşulda sabit tutmak"],a:4,e:"Maliye politikasının temel amaçları istikrar, istihdam, büyüme ve dağılım gibi hedeflerdir; belirli bir kuru her koşulda tutmak zorunlu temel amaç değildir."},
    {q:"Verginin geriye yansıması neyi ifade eder?",o:["Verginin tüketiciye aktarılmasını","Vergi yükünün girdi sağlayıcılarına veya üretim faktörlerine daha düşük ödeme yoluyla aktarılmasını","Verginin gelecek döneme ertelenmesini","Verginin silinmesini"],a:1,e:"Geriye yansımada yük, üretim zincirinin önceki aşamalarına veya üretim faktörlerine doğru aktarılır."},
    {q:"Kamu borcunun vadesinin uzatılmasına ne ad verilir?",o:["Konversiyon","Konsolidasyon","Monetizasyon","İtfa"],a:1,e:"Konsolidasyon, kısa vadeli borcun daha uzun vadeli borca dönüştürülmesi anlamına gelir."},
    {q:"Yüksek faizli kamu borcunun daha düşük faizli yeni borçla değiştirilmesi hangi kavramdır?",o:["Konsolidasyon","Konversiyon","Refinansman dışı transfer","Yansıma"],a:1,e:"Konversiyon, borcun faiz yükünü düşürmek amacıyla mevcut borç koşullarının değiştirilmesidir."},
    {q:"Kamu borçlanmasının faiz oranlarını yükselterek özel yatırımları azaltması hangi etkiyle açıklanır?",o:["Çarpan etkisi","Dışlama etkisi","Pigou etkisi","Gelir etkisi"],a:1,e:"Kamu borçlanması mali fonlara talebi artırıp faizleri yükselterek özel yatırımları geriletebilir; buna dışlama etkisi denir."}
  ]
};