window.SAYISTAY_DATA.quizzes[1] = {
  title: "Maliye — 20 Soruluk Gün Sonu Testi",
  questions: [
    {q:"Kamu maliyesinin temel inceleme alanı aşağıdakilerden hangisidir?",o:["Yalnız özel sektör yatırımları","Kamu gelirleri, kamu harcamaları ve bunların ekonomik-toplumsal etkileri","Yalnız para arzı","Sadece dış ticaret"],a:1,e:"Kamu maliyesi; kamu gelirlerini, kamu harcamalarını, bütçeyi, borçlanmayı ve bunların ekonomi üzerindeki etkilerini inceler."},
    {q:"Tam kamusal malın iki temel özelliği hangisidir?",o:["Rakiplik ve dışlanabilirlik","Rakipsizlik ve dışlanamazlık","Bölünebilirlik ve fiyatlandırılabilirlik","Özel mülkiyet ve rekabet"],a:1,e:"Tam kamusal mallarda bir kişinin tüketimi diğerinin tüketimini azaltmaz ve ödeme yapmayanları tüketimden dışlamak güçtür."},
    {q:"Aşağıdakilerden hangisi tam kamusal mala en uygun örnektir?",o:["Ekmek","Ulusal savunma","Özel okul hizmeti","Binek otomobil"],a:1,e:"Ulusal savunma, rakipsizlik ve dışlanamazlık özellikleri nedeniyle klasik tam kamusal mal örneğidir."},
    {q:"Bedavacılık sorunu en doğrudan hangi özellikle ilişkilidir?",o:["Dışlanamazlık","Azalan marjinal fayda","Ölçek ekonomisi","Tam rekabet"],a:0,e:"Tüketimden dışlamanın güç olması, kişilerin ödeme yapmadan faydalanma eğilimini artırır ve bedavacılık sorununu doğurur."},
    {q:"Yarı kamusal mallar için aşağıdakilerden hangisi doğrudur?",o:["Hiçbir özel fayda sağlamazlar","Hem bireysel hem toplumsal fayda doğurabilirler","Mutlaka ücretsiz sunulurlar","Sadece merkezi yönetim üretir"],a:1,e:"Eğitim ve sağlık gibi yarı kamusal mallar bireye doğrudan özel fayda sağlarken topluma da dışsal faydalar yaratabilir."},
    {q:"Erdemli mal kavramı en iyi nasıl açıklanır?",o:["Toplumun tüketiminin yetersiz kalabileceği ve kamu tarafından teşvik edilebilen mal","Tüketimi daima yasaklanan mal","Sadece zenginlerin tükettiği mal","Tamamen dışlanamaz mal"],a:0,e:"Erdemli mallar, bireylerin toplumsal açıdan arzu edilenden daha az tüketebileceği ve bu nedenle kamu müdahalesiyle teşvik edilebilen mallardır."},
    {q:"Aşağıdakilerden hangisi erdemsiz mala örnek verilebilir?",o:["Aşı","Temel eğitim","Sigara","Kamu parkı"],a:2,e:"Erdemsiz mallarda bireysel tercih, toplumsal maliyetleri yeterince dikkate almayabilir; tütün ürünleri klasik örnektir."},
    {q:"Bir fabrikanın çevreye maliyet yüklemesi hangi tür dışsallıktır?",o:["Pozitif tüketim dışsallığı","Negatif üretim dışsallığı","Pozitif üretim dışsallığı","Mali dışsallık"],a:1,e:"Üretim faaliyeti üçüncü kişilere telafi edilmeyen zarar veriyorsa negatif üretim dışsallığı söz konusudur."},
    {q:"Bir kişinin aşı olması çevresindekilerin hastalık riskini de azaltıyorsa bu durum nedir?",o:["Negatif üretim dışsallığı","Pozitif tüketim dışsallığı","Monopol gücü","Kamu borcu"],a:1,e:"Tüketicinin eylemi üçüncü kişilere fayda sağlıyorsa pozitif tüketim dışsallığı ortaya çıkar."},
    {q:"Negatif dışsallık bulunan bir piyasada, diğer koşullar sabitken serbest piyasa üretim miktarı toplumsal optimuma göre genellikle nasıldır?",o:["Daha düşüktür","Daha yüksektir","Daima eşittir","Sıfırdır"],a:1,e:"Özel maliyet toplumsal maliyetten düşük algılandığı için negatif dışsallıkta piyasa genellikle aşırı üretim yapar."},
    {q:"Pozitif dışsallık bulunan bir piyasada serbest piyasa tüketim/üretim miktarı toplumsal optimuma göre genellikle nasıldır?",o:["Daha yüksektir","Daha düşüktür","Daima eşittir","Sonsuzdur"],a:1,e:"Dışsal faydalar piyasa kararına tam yansımadığı için pozitif dışsallıkta piyasa miktarı toplumsal optimumun altında kalabilir."},
    {q:"Pigou vergisinin temel amacı nedir?",o:["Pozitif dışsallığı artırmak","Negatif dışsallığın dışsal maliyetini karar vericiye yansıtmak","Kamusal malları özelleştirmek","Gelir vergisini kaldırmak"],a:1,e:"Pigou vergisi, negatif dışsallığın marjinal dışsal maliyetini fiyat mekanizmasına dahil ederek özel ve toplumsal maliyetleri yaklaştırmayı amaçlar."},
    {q:"Aşağıdakilerden hangisi piyasa başarısızlığı nedeni değildir?",o:["Dışsallıklar","Kamusal mallar","Eksik bilgi","Tam rekabet altında tam bilgi ve dışsallık yokluğu"],a:3,e:"Tam rekabet, tam bilgi ve dışsallık yokluğu piyasa başarısızlığı değil, etkin piyasa sonucunu destekleyen koşullardır."},
    {q:"Asimetrik bilgi hangi piyasa başarısızlığıyla ilgilidir?",o:["Tarafların aynı bilgiye sahip olmaması","Malların mutlaka ücretsiz olması","Kamu bütçesinin denk olması","Vergilerin dolaysız olması"],a:0,e:"Asimetrik bilgi, işlem taraflarından birinin diğerinden daha fazla veya daha kaliteli bilgiye sahip olmasıdır."},
    {q:"Kamu harcamalarının ekonomik sınıflandırılmasında aşağıdakilerden hangisi yer alabilir?",o:["Cari, yatırım ve transfer harcamaları","Sadece personel ve vergi","Yalnız savunma ve eğitim","Yalnız merkezi ve yerel"],a:0,e:"Klasik ekonomik ayrım cari, yatırım ve transfer harcamalarıdır; sınıflandırma harcamanın ekonomik niteliğine bakar."},
    {q:"Transfer harcamalarının ayırt edici özelliği nedir?",o:["Karşılığında doğrudan mal veya hizmet alınmaması","Mutlaka bina yapımına gitmesi","Sadece belediyelerce yapılması","Her zaman üretim kapasitesini doğrudan artırması"],a:0,e:"Transfer harcamalarında kamu, doğrudan bir mal veya hizmet satın almadan gelir/servet aktarımı yapar."},
    {q:"Bir kamu hastanesi binasının yapımı hangi tür harcamaya en yakındır?",o:["Transfer harcaması","Yatırım harcaması","Borç faizi","Cari transfer"],a:1,e:"Yeni ve uzun ömürlü bir kamu sermaye varlığı oluşturduğu için yatırım harcamasıdır."},
    {q:"Kamu harcamalarının zaman içinde artmasını açıklayan Wagner Kanunu neyi vurgular?",o:["Ekonomik ve toplumsal gelişmeyle kamu faaliyetlerinin genişlemesini","Vergilerin tamamen kalkmasını","Para arzının sabit kalmasını","Kamu harcamalarının daima azalmasını"],a:0,e:"Wagner yaklaşımında sanayileşme, kentleşme ve gelir artışıyla kamu hizmetlerine talep ve kamu faaliyetlerinin kapsamı genişler."},
    {q:"Peacock-Wiseman sıçrama tezi kamu harcamalarındaki artışı nasıl açıklar?",o:["Savaş ve kriz gibi olağanüstü dönemlerde kabul edilebilir vergi yükünün ve harcama düzeyinin sıçramasıyla","Sadece nüfus azalmasıyla","Faizlerin daima düşmesiyle","Özel yatırımın yasaklanmasıyla"],a:0,e:"Olağanüstü dönemler harcama ve vergi yükünü yukarı taşır; kriz sonrasında harcamalar eski düzeye tam dönmeyebilir."},
    {q:"Nüfus artışı ve kentleşmenin kamu harcamalarını artırması hangi açıklamaya dayanır?",o:["Kamu hizmetlerine yönelik talep ve altyapı ihtiyacının artmasına","Kamusal malların tamamen ortadan kalkmasına","Vergilerin sıfırlanmasına","Kamu borcunun otomatik olarak yok olmasına"],a:0,e:"Daha büyük ve kentleşmiş nüfus; ulaşım, altyapı, eğitim, sağlık, güvenlik gibi hizmetlere talebi yükselterek kamu harcamalarını artırabilir."}
  ]
};